### ISSUE TITLE
Export AvatarProps as a type

### ISSUE THREAD

**Issue by axantillon** [readyplayerme/visage#24]
hey!

I was looking around but couldn't exactly find where to make the change myself and open a PR, but could you guys export the AvatarProps interface?

I'm building using Nextjs@13 and, to include the "Avatar" component, I have to wrap it in another component that uses the 'use client' directive. However, I can't extend the props from the "Avatar" component to the wrapper while being type safe because AvatarProps isn't exported.

<img width="1008" alt="Screenshot 2023-04-24 at 3 36 54 PM" src="https://user-images.githubusercontent.com/38710228/234122340-deb62293-e6d6-4cc7-81ba-aac4aa613f4e.png">

**Comment by axantillon** [comment]
Hey, 
Just following up because I just tried to build my project and I keep getting this error:
![image](https://user-images.githubusercontent.com/38710228/234407501-7622e8df-808e-4cdf-828e-b83e02984f02.png)

Could you please fix asap? :)

**Comment by Zaehiel** [comment]
Hi!
Thanks for the feedback.
Can you provide reproduction sandbox?

**Comment by axantillon** [comment]
Hey,

I tried creating a sandbox to recreate but since the issue comes up at build time and when using typescript, I can't reproduce.
CodeSandbox runs Next.js products on the cloud where they run a dev server.
I haven't use CodeSandbox that much so I may be missing something.

The issue simply is that AvatarProps isn't exported from the types.d.ts file.
`Avatar: FC<AvatarProps>` is, but that doesn't allow you to define another component to also take in `AvatarProps`.

**Comment by axantillon** [comment]
Nvm, I got around it by declaring my wrapper component for the `Avatar` component by declaring it as `typeof Avatar`.
