### ISSUE TITLE
.glb animations

### ISSUE THREAD

**Issue by Radutiu-Horatiu** [readyplayerme/visage#33]
I see that you guys are using that `male-idle.glb` animation in the demo. Can you tell me where did you get that animation from and how? Is there a way I can convert other Mixamo animations to .glb visage supported format?

Thanks!

**Comment by Zaehiel** [comment]
Hi @Radutiu-Horatiu 
We have plans to add .fbx animation support in the Soon™ future. Until then you'll have to check the internet on what tool would fit your needs to convert .fbx to .glb.

Also, have you looked into [FBX loader](https://sbcode.net/threejs/loaders-fbx/), you could try to load the.fbx animation and then proxy it as `Blob` or `base64` into Visage components via `animationSrc` prop.

**Comment by Radutiu-Horatiu** [comment]
@Zaehiel maybe can you try and find out what tool could be used to convert like that `male-idle.glb` model was? I tried with numerous tools, I even got an expert in blender from fiverr to try and sort it out but could not make it :)
