### ISSUE TITLE
@Zaehiel maybe can you try and find out what tool could be used to convert like that `male-idle.glb` model was? I tried with numerous tools, I even got an expert in blender from fiverr to try and sort it out but could not make it :)

### ISSUE THREAD

**Issue by Radutiu-Horatiu** [readyplayerme/visage#35]
@Zaehiel maybe can you try and find out what tool could be used to convert like that `male-idle.glb` model was? I tried with numerous tools, I even got an expert in blender from fiverr to try and sort it out but could not make it :)

_Originally posted by @Radutiu-Horatiu in https://github.com/readyplayerme/visage/issues/33#issuecomment-1583285652_

**Comment by Zaehiel** [comment]
Hi @Radutiu-Horatiu,

I hope this message finds you well. I wanted to take a moment to address the question you raised and provide some clarification regarding the matter at hand. Firstly, I want to express my gratitude for your active participation and engagement with our repository. Your contributions are highly valued, and we appreciate your efforts in making it a vibrant community.

However, upon carefully reviewing the details you provided, I must inform you that the issue you mentioned appears to be unrelated to the repository's specific focus. As a result, it will be necessary for us to close this particular matter. Please understand that this decision is not a reflection of the importance or relevance of your question, but rather a means to maintain a streamlined and organized repository environment.

We strive to ensure that our repository remains dedicated to addressing issues directly tied to its purpose, thereby benefiting all users who visit and engage with the platform. To that end, I would suggest seeking assistance or guidance in a more appropriate forum or platform where you can receive the specialized support you require for the matter in question.

I want to emphasize that your inquiry is valuable, and we encourage you to continue participating actively in our repository. Please feel free to raise any concerns or questions that align with the intended scope of the repository, and we will be more than happy to assist you to the best of our abilities.

Once again, I sincerely appreciate your understanding in this matter. Your involvement plays a crucial role in fostering a collaborative and supportive community, and we value your continued contributions. If you have any further inquiries or concerns regarding the repository's guidelines or related topics, please don't hesitate to reach out, and we'll be glad to provide any necessary assistance.

**Comment by Radutiu-Horatiu** [comment]
This answer looks like ChatGPT generated :))) Ok mate, I will figure it out on my own.
