### ISSUE TITLE
Window specific code causes server side error in NextJS app

### ISSUE THREAD

**Issue by TowhidKashem** [readyplayerme/visage#56]
hey guys,

I know you're working actively on this new project but just a heads up.. The recent addition of window specific code introduced a bug in NextJS where the code is run server side and fails due to window being a browser thing. I'm maintaining a fork anyway so I made the fixes locally here:

https://github.com/TowhidKashem/visage/commit/8c0a5bacc37f619d0f637a373be0aac6df6e0338 (ignore the first 2 build files)

please wrap all window calls in a check when you get a chance, and keep up the great work!

**Comment by Zaehiel** [comment]
@TowhidKashem Thanks for the feedback. Fixed in `v4.10.2`
